config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :subscriptions
  resources :dashboards, path: 'dashboard'
  resources :accounts
  resources :settings
  resources :projects
  devise_for :users
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :account
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy!

    respond_to do |format|
      format.html { redirect_to settings_path, status: :see_other, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.fetch(:setting, {})
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<div id="<%= dom_id setting %>">
</div>

app/views/settings/edit.html.erb
<% content_for :title, "Editing setting" %>

<h1>Editing setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Show this setting", @setting %> |
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Settings" %>

<h1>Settings</h1>

<div id="settings">
  <% @settings.each do |setting| %>
    <%= render setting %>
    <p>
      <%= link_to "Show this setting", setting %>
    </p>
  <% end %>
</div>

<%= link_to "New setting", new_setting_path %>

app/views/settings/new.html.erb
<% content_for :title, "New setting" %>

<h1>New setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @setting %>

<div>
  <%= link_to "Edit this setting", edit_setting_path(@setting) %> |
  <%= link_to "Back to settings", settings_path %>

  <%= button_to "Destroy this setting", @setting, method: :delete %>
</div>